services:
    mailpit:
        image: axllent/mailpit:v1.20
        container_name: mailpit
        command: ["--smtp-auth-accept-any", "--smtp-auth-allow-insecure"]
        ports:
            - "1025:1025"
            - "8025:8025"
